# Generated by Django 4.2.2 on 2023-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_student_file_remove_student_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('speed', models.IntegerField(default=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
